name: Build and Publish Docker Image

on:
  push:
    branches:
      - "**"
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    name: Build Go Project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Build Project
        working-directory: ./src
        run: |
          go mod tidy
          go build -v ./...

  publish:
    name: Build and Publish Docker Image
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tag name
        id: tag_name
        run: |
          TAG=${GITHUB_REF##*/}
          TAG_NO_V=${TAG#v}
          echo "Tag without 'v': $TAG_NO_V"
          echo "TAG_NO_V=$TAG_NO_V" >> $GITHUB_ENV

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/snekussaurier/minban-backend:${{ steps.tag_name.outputs.TAG_NO_V }}