name: Render D2 Files to SVG

on:
  push:
    branches:
      - "main"
    paths:
      - 'doc/d2/**'
    
jobs:
  render-diagrams:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Render .d2 files to SVG
        run: |
            for file in "doc/d2"/* 
            do
                # Extract filename without extension
                filename=$(basename "$file" .d2)
                echo $filename
                # Check if the file exists and run D2Lang to render the .d2 file to .svg
                if [[ -f "$file" ]]; then
                docker run --rm -v ${GITHUB_WORKSPACE}:/workspace --user $(id -u):$(id -g) ghcr.io/snekussaurier/d2lang-docker:latest d2 "/workspace/doc/d2/$filename.d2" "/workspace/doc/img/database/$filename.svg"
                fi
            done

      - name: Commit files to repository
        run: |
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add  doc/*.svg
            git commit -m "generated svg"
            git push
